<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.104.2" />
		<PackageReference Include="CloudinaryDotNet" Version="1.29.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="PdfPig" Version="0.1.14" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TutorPlatform.Core\TutorPlatform.Core.csproj" />
		<ProjectReference Include="..\TutorPlatform.Infrastructure\TutorPlatform.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\uploads\documents\" />
	</ItemGroup>

</Project>